language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: dMd9sAPnnGVSFbtNEzM5B9uh03bXoUMHRWe+75jxUDhvX98wEJIYUcyBYGw1YOmcSoKUziBwDhoaREC+cWXg2MFZK8tMGlZBbm0YtI7g+I6xDMJvOBQMlPRhOGmlcwYiQzM6kE7m5go/flRtxw7NxxhpQv8VNQ/dV4XRzWKgdVpUtPIxv0IApk4cfZh8SAJpPJZFBCdlI5SLpt2UVuszrwf8AGC3qKDnIzTWTsiR/Vyjz4vGIM3PuWQj8yFIA8vQrf0KmPMBLGVIDCmn5B77LlJ4LJbj74EVk3sOFK8nX8uz0Q+wZxAle8UvYNWvh/Di4637wIy5WgKuvf4WWLlo2PurRl0MbAmEY9wNh5EIjxcaY4+FZW3OYdKavYqOYJM36HZi1zDWMiw5gUEenVMuasg1VXuBuDYY11zZ1IjIdH6kHKnSdWUazSu4KozfZ+AqHONv2NcnHQnjjXNG0KpD/dIeU1oEAoV5Wy9jblWyl/iZZsomIvbKPj0Ymj7hyd4lA1AKWwpFIVE5xQkWtIXlSgBxi/dvnfSEnxGlyeUj8XhViyNN72MQOsla+YNaFigimHWFfOCNiGl612d0HzdAPa1NVuXuukMkojGK9t+HdmhtRgLpSENqw4xJpUsToTD60993GRVIpOAD7ULsMPaP3zJ1fUyW31G6pJfG/c8/jE0=
  app: morning-harbor-25215
  on:
    repo: annasheik/blog-api-mongoose
